name: flutter_riverpod_movie_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: null
  flutter_slidable: ^1.1.0
  flutter_spinkit: ^5.1.0
  google_fonts: ^2.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: null
  modal_bottom_sheet: ^2.0.0
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2
  hive_generator: ^1.1.1

flutter_native_splash:
  color: "#191a32"
  

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
